config/routes.rb
Rails.application.routes.draw do
  get 'backoffice/index'

  get 'home/index'

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders do
    resources :order_has_meals
  end

  resources :meal_categories do
    resources :meals
  end

  root 'home#index'
end

app/models/order_has_meal.rb
class OrderHasMeal < ApplicationRecord
  belongs_to :order
  belongs_to :meal
end

app/controllers/order_has_meals_controller.rb
class OrderHasMealsController < ApplicationController
  after_action :set_order_price, only: [:create, :update]

  def create
    @order = Order.find(session[:current_order_id])
    @meal = Meal.find(params[:order_has_meal][:meal_id])

    attrs = order_has_meal_params.clone
    attrs[:price] = (@meal.price*attrs[:quantity].to_f)

    @order_has_meal = @order.order_has_meals.create(attrs)
    redirect_to home_index_path
  end

  def update
    @order = Order.find(session[:current_order_id])
    @meal = Meal.find(params[:order_has_meal][:meal_id])
    @order_has_meal = @order.order_has_meals.find_by(meal_id: @meal.id)

    attrs = order_has_meal_params.clone
    attrs[:price] = (@meal.price*attrs[:quantity].to_f)

    if @order_has_meal.update(attrs)
      redirect_to home_index_path
    else
      render 'order_has_meals/form'
    end
  end

  private
    def order_has_meal_params
      params.require(:order_has_meal).permit(:quantity, :price, :meal_id)
    end

    def set_order_price
      @order = Order.find(session[:current_order_id])
      @order.price = 0

      @order.order_has_meals.each do |m|
        @order.price += m.price
      end

      @order.save
    end
end

app/helpers/order_has_meals_helper.rb
module OrderHasMealsHelper
end

app/views/order_has_meals/_form.html.erb
<%- if OrderHasMeal.find_by(meal_id: meal_id, order_id: session[:current_order_id]) %>
  <%= form_with model: Order.find(session[:current_order_id]).order_has_meals.find_by(meal_id: meal_id),
    url: order_order_has_meal_path(session[:current_order_id],
                                   OrderHasMeal.find_by(meal_id: meal_id, order_id: session[:current_order_id]).id) do |form| %>
    <p>
      <%= form.label "Quantidade" %><br>
      <%= form.number_field :quantity, min: 0 %>
    </p>

    <%= form.hidden_field :meal_id, value: meal_id %>

    <p id="ms">
      <%= form.submit "atualizar" %>
    </p>
  <% end %>
<% else %>
  <%= form_with scope: :order_has_meal, url: order_order_has_meals_path(session[:current_order_id]) do |form| %>
    <p>
      <%= form.label "Quantidade" %><br>
      <%= form.number_field :quantity, min: 0 %>
    </p>

    <%= form.hidden_field :meal_id, value: meal_id %>

    <p id="ms">
      <%= form.submit "adicionar" %>
    </p>
  <% end %>
<% end -%>