config/routes.rb
Rails.application.routes.draw do
  get 'backoffice/index'

  get 'home/index'

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders do
    resources :order_has_meals
  end

  resources :meal_categories do
    resources :meals
  end

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @meal_categories = MealCategory.all
    @order = Order.find(session[:current_order_id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => "reload" %>
<%= stylesheet_link_tag "header", media: "all", "data-turbolinks-track" => "reload" %>

<link href="https://fonts.googleapis.com/css?family=Amaranth" rel="stylesheet">

<header>
  <%= render "shared/navbar" %>
  <%- if user_signed_in? %>
    <h1 class="welcome">
      Bem-vindo, <%= current_user.name %>
    </h1>
    <h6 class="welcome">
      Monte seu prato, escolha sua salada,
      molho, prato principal, guarnição e bebida
    </h6>
  <% else %>
    <h1 class="welcome">
      Monte o seu prato
    </h1>
    <h6 class="welcome">
      Escolha sua salada, molho, prato principal, guarnição e bebida
    </h6>
  <% end -%>
</header>

<div class="wrapper">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash" if msg.length > 0 %>
  <% end %>

  <%= render @meal_categories %>
  <%= render @order %>
  <div class="fs">
    <%- if user_signed_in? %>
      <%= form_with model: @order do |form| %>
        <%= form.hidden_field :status, value: 1 %>
        <p>
          <%= form.submit "finalizar" %>
        </p>
      <% end %>
    <% else %>
      <span> Você precisa estar logado para finalizar o pedido</span>
      <div class="links">
        <%= link_to 'Entrar', new_session_path(:user) %>
        <%= link_to 'Criar conta', new_registration_path(:user) %>
      </div>
    <% end -%>
  </div>

  <%- if user_signed_in? %>
    <p id="header2"> Pedidos anteriores mais recentes</p>
    <%= render current_user.orders.where.not(id: @order.id).reverse.first(5) %>
  <% end %>
</div>

<br>
<br>
<br>
<p>----------PROVISORIO----------</p>
<%= link_to 'Criar categoria', new_meal_category_path %>
<br>
<%= link_to 'Categorias', meal_categories_path %>
<br>
<%= link_to 'Pratos', orders_path %>