config/routes.rb
Rails.application.routes.draw do
  get 'backoffice/index'

  get 'home/index'

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders do
    resources :order_has_meals
  end

  resources :meal_categories do
    resources :meals
  end

  root 'home#index'
end

app/models/meal_category.rb
class MealCategory < ApplicationRecord
  has_many :meals
  validates :name, presence: true
end

app/controllers/meal_categories_controller.rb
class MealCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin

  def index
    @meal_categories = MealCategory.all
  end

  def show
    @meal_category = MealCategory.find(params[:id])
  end

  def new
    @meal_category = MealCategory.new
  end

  def create
    @meal_category = MealCategory.new(meal_category_params)

    if @meal_category.save
      redirect_to @meal_category
    else
      render 'new'
    end
  end

  private
  def meal_category_params
    params.require(:meal_category).permit(:name)
  end
end

app/helpers/meal_categories_helper.rb
module MealCategoriesHelper
end

app/views/meal_categories/_meal_category.html.erb
<p id="category_header"><%= meal_category.name %></p>

<div class="meal_category">
  <%- if !meal_category.meals.empty? %>
    <div class="meal">
      <%= render meal_category.meals, not_render: false %>
    </div>
  <% else %>
    <p id="category_text"> Parece que não há nada aqui </p>
  <% end -%>
</div>

app/views/meal_categories/index.html.erb
<%= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => "reload" %>

<div class="wrapper">
  <br>
  <%= link_to 'Backoffice', backoffice_index_path %>
  <br>
  <%= link_to 'Home', home_index_path %>
  <br>
  <%= link_to 'Pedidos', orders_path %>

  <h1>Lista categorias</h1>

  <table>
    <tr>
      <th>Nome</th>
    </tr>

    <% @meal_categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Mostrar', meal_category_path(category) %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to 'Criar categoria', new_meal_category_path %>
</div>

app/views/meal_categories/new.html.erb
<%= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => "reload" %>

<div class="wrapper">
  <br>
  <%= link_to 'Backoffice', backoffice_index_path %>
  <br>
  <%= link_to 'Home', home_index_path %>
  <br>
  <%= link_to 'Categorias', meal_categories_path %>
  <br>
  <%= link_to 'Pedidos', orders_path %>

  <h1>Nova categoria</h1>

  <%= form_with scope: :meal_category, url: meal_categories_path, local: true do |form| %>

    <% if @meal_category.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@meal_category.errors.count, "erro") %> proibiram
          que essa categoria seja salva:
        </h2>
        <ul>
          <% @meal_category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.submit "Criar categoria" %>
    </p>

  <% end %>
</div>

app/views/meal_categories/show.html.erb
<%= stylesheet_link_tag "backoffice", media: "all", "data-turbolinks-track" => "reload" %>

<div class="wrapper">
  <br>
  <%= link_to 'Backoffice', backoffice_index_path %>
  <br>
  <%= link_to 'Home', home_index_path %>
  <br>
  <%= link_to 'Categorias', meal_categories_path %>
  <br>
  <%= link_to 'Pedidos', orders_path %>

  <h1>
    <%= @meal_category.name %>
  </h1>

  <p>---------------------------------------------</p>
  <strong>Adicionar refeição</strong>
  <p>---------------------------------------------</p>
  <%= render 'meals/form' %>

  <%- if !@meal_category.meals.empty? %>
    <p>---------------------------------------------</p>
    <strong>Refeições existentes</strong>
    <p>---------------------------------------------</p>
    <%= render @meal_category.meals, not_render: true  %>
  <% end -%>
</div>