config/routes.rb
Rails.application.routes.draw do
  get 'backoffice/index'

  get 'home/index'

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders do
    resources :order_has_meals
  end

  resources :meal_categories do
    resources :meals
  end

  root 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :status, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :status, numericality: { greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 4,
                                    only_integer: true}
  has_many :order_has_meals
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order
    else
      render 'new'
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.status = 1
    @order.save

    flash[:notice] = "Obrigado. Seu pedido foi recebido."

    redirect_to home_index_path
  end

  private
  def order_params
    params.require(:order).permit(:status, :price, :user_id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<%- if order.id == session[:current_order_id]%>
  <div class="order header">
    <p id="header"> Seu pedido </p>
    <p>
      <span>ID do pedido:</span>
      <%= order.id %>
    </p>
    <p>
      <span>Situação:</span>
      <%= order.status %>
    </p>
  </div>

  <%- if order.order_has_meals.any? %>
    <div class="order items">
      <% order.order_has_meals.each do |meal_order| %>
        <div class="item">
          <p>
            <br />
            Nome: <%= Meal.find(meal_order.meal_id).name %>
            <br>
            Preço unitário: <%= Meal.find(meal_order.meal_id).price %>
            <br>
            Quantidade: <%= meal_order.quantity %>
            <br>
            Preço: R$<%= meal_order.price %>
          </p>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="vazio">
      <p>Parece que você ainda não selecionou nada.</p>
    </div>
  <% end -%>
  <div class="order footer">
    <p>
      <strong>Preço total:</strong>
      R$ <%= order.price %>
    </p>
  </div>
<% else %>
  <%- if order.id != session[:current_order_id]%>
    <div class="order old">
      <p>
        <span>ID do pedido:</span>
        <%= order.id %>
      </p>
      <p>
        <span>Situação:</span>
        <%= order.status %>
      </p>
      <p>
        <span>Items:</span>
        <br />
        <table>
          <% order.order_has_meals.each do |meal_order| %>
            <tr>
              <td><%= Meal.find(meal_order.meal_id).name %>&nbsp;&nbsp;</td>
              <td>x<%= meal_order.quantity %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
              <td>R$<%= meal_order.price %></td>
            </tr>
          <% end %>
        </table>
      </p>
      <p>
        <strong>Preço total:</strong>
        R$ <%= order.price %>
      </p>
    </div>
  <% end -%>
<% end -%>

app/views/orders/index.html.erb
<%= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => "reload" %>

<div class="wrapper">
  <br>
  <%= link_to 'Home', home_index_path %>
  <br>
  <%= link_to 'Backoffice', backoffice_index_path %>
  <br>
  <%= link_to 'Categorias', meal_categories_path %>

  <h1>Lista pedidos</h1>

  <table>
    <tr>
      <th>ID</th>
      <th>Status</th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Mostrar', order_path(order) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/orders/new.html.erb
<h1>Prato</h1>
<%= form_with scope: :order, url: orders_path, local: true do |form| %>

  <% if @order.errors.any? %>
    <div id="error_explanation">
      <strong>
        <%= pluralize(@order.errors.count, "erro") %> probiram
        a criacao do prato:
      </strong>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :status %><br>
    <%= form.number_field :status, in: 0...5 %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<%= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => "reload" %>

<div class="wrapper">
  <br>
  <%= link_to 'Home', home_index_path %>
  <br>
  <%= link_to 'Backoffice', backoffice_index_path %>
  <br>
  <%= link_to 'Categorias', meal_categories_path %>
  <br>
  <%= link_to 'Pedidos', orders_path %>

  <h1>Pedido</h1>
  <p>
    <strong>ID:</strong>
    <%= @order.id %>
  </p>

  <p>
    <strong>Situação:</strong>
    <%= @order.status %>
  </p>

  <% if @order.status = 1 %>
    <p>
      <strong>ID do usuário:</strong>
      <%= @order.user_id %>
    </p>
  <% end %>

  <p>
    <strong>Preço total:</strong>
    <%= @order.price %>
  </p>

  <h2>Itens</h2>
  <table>
    <tr>
      <th>Nome da refeição</th>
      <th>ID da refeição</th>
      <th>Quantidade</th>
      <th>Preço</th>
    </tr>
    <% @order.order_has_meals.each do |meal_order| %>
      <tr>
        <td><%= Meal.find(meal_order.meal_id).name %></td>
        <td><%= meal_order.meal_id %></td>
        <td><%= meal_order.quantity %></td>
        <td><%= meal_order.price %></td>
      </tr>
    <% end %>
  </table>
</div>